### ISSUE TITLE
Lab 3b: Implement SAP architecture on Azure VMs running Windows

### ISSUE THREAD

**Issue by sathishneelam** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#12] opened 2021-04-22 10:04 UTC
While doing Task 3: Deploy Azure Resource Manager template provisioning Azure VMs running Windows Server 2016 that will host a highly available SAP NetWeaver deployment Step 5:Back on the SAP NetWeaver 3-tier (managed disk) blade, initiate deployment with the following settings:

we're getting the extension failed issue

![image](https://user-images.githubusercontent.com/58003174/115696052-ef8b7400-a37f-11eb-9c6d-a9aaa03ff7b5.png)

Can you please check into this

**Comment by GhumanNavneet** [comment] 2021-04-29 07:28
any update on this

**Comment by eric-camplin** [comment] 2021-04-29 16:08
Investigating - thank you for the follow up

**Comment by polichtm** [comment] 2021-05-06 01:59
This works for me without any issues:
![image](https://user-images.githubusercontent.com/10284906/117231418-2f754100-aded-11eb-83e0-01b7d009cd43.png)
Pls give it another try
rgds
Marcin

**Comment by polichtm** [comment] 2021-05-06 02:08
Closing as a duplicate of #14

**Closed by polichtm** 2021-05-06 02:08 UTC
